import {CFG,createMatch,step,canPlace,pocketFor} from './simulation.js';
const canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d'),start=document.querySelector('#start'),hud=document.querySelector('#hud'),tray=document.querySelector('#tray'),shop=document.querySelector('#shop'),result=document.querySelector('#result');
const buildBtn=document.querySelector('#buildBtn'),abilityBtn=document.querySelector('#abilityBtn'),joystick=document.querySelector('#joystick');
let W=1,H=1,D=1,state=null,role=null,paused=false,last=performance.now(),acc=0,selected='wall',camera={x:0,y:0},keys=new Set(),pointer={x:0,y:0},placing=false,stick={id:null,x:0,y:0};const defs=CFG.structures;
function resize(){const r=canvas.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);visualViewport?.addEventListener('resize',resize);resize();
function begin(r){role=r;state=createMatch(r,7);start.classList.add('hidden');result.classList.add('hidden');hud.classList.remove('hidden');joystick.classList.remove('hidden');buildBtn.classList.toggle('hidden',r!=='builder');abilityBtn.classList.toggle('hidden',r!=='hunter');tray.classList.add('hidden');shop.classList.add('hidden');last=performance.now();acc=0}
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>begin(b.dataset.role));document.querySelector('#again').onclick=()=>{state=null;result.classList.add('hidden');hud.classList.add('hidden');joystick.classList.add('hidden');buildBtn.classList.add('hidden');abilityBtn.classList.add('hidden');start.classList.remove('hidden')};
function buildTray(){tray.innerHTML='';for(const [k,d] of Object.entries(defs)){const b=document.createElement('button');b.innerHTML=`${d.name}<span>${d.m} M · ${d.c} C</span>`;b.onclick=()=>{selected=k;placing=true;tray.classList.add('hidden')};tray.append(b)}}buildTray();buildBtn.onclick=()=>tray.classList.toggle('hidden');abilityBtn.onclick=()=>{if(state)state._dash=true};
function shopUi(){shop.innerHTML='';for(const [k,n] of [['damage','Weapon'],['hp','Vitality'],['speed','Speed'],['siege','Siege'],['bounty','Bounty']]){const lv=state.hunter.level[k]||0,c=70+lv*65,b=document.createElement('button');b.innerHTML=`${n} ${lv+1}<span>${c} bounty</span>`;b.onclick=()=>state._buy=k;shop.append(b)}}
addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space'&&role==='hunter')state._dash=true});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();stick.x=stick.y=0});addEventListener('escapee:pause',()=>{keys.clear();stick.x=stick.y=0});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=e.clientX-r.left;pointer.y=e.clientY-r.top});canvas.addEventListener('pointerdown',()=>{if(!state||role!=='builder'||!placing)return;const wx=pointer.x+camera.x-W/2,wy=pointer.y+camera.y-H/2,gx=Math.floor(wx/32),gy=Math.floor(wy/32);state._place={gx,gy,structure:selected};placing=false});
joystick.addEventListener('pointerdown',e=>{stick.id=e.pointerId;stick.ox=e.clientX;stick.oy=e.clientY;joystick.setPointerCapture(e.pointerId)});joystick.addEventListener('pointermove',e=>{if(e.pointerId!==stick.id)return;stick.x=Math.max(-1,Math.min(1,(e.clientX-stick.ox)/40));stick.y=Math.max(-1,Math.min(1,(e.clientY-stick.oy)/40))});const release=e=>{if(stick.id===e.pointerId){stick.id=null;stick.x=stick.y=0}};joystick.addEventListener('pointerup',release);joystick.addEventListener('pointercancel',release);
function command(){if(!state)return[];let x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+stick.x,y=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'))+stick.y;const out=[];if(x||y)out.push({type:'move',actor:role==='hunter'?'hunter':0,x,y});if(state._dash){out.push({type:'dash'});state._dash=false}if(state._buy){out.push({type:'buy',key:state._buy});state._buy=null}if(state._place){out.push({type:'place',actor:0,...state._place});state._place=null}return out}
function screen(x,y){return{x:x-camera.x+W/2,y:y-camera.y+H/2}}
function drawTerrain(){ctx.fillStyle='#111b20';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-camera.x,H/2-camera.y);ctx.fillStyle='#26352f';ctx.fillRect(0,0,38*32,34*32);ctx.fillStyle='#10171b';const rs=[{x:0,y:0,w:38,h:2},{x:0,y:32,w:38,h:2},{x:0,y:0,w:2,h:34},{x:36,y:0,w:2,h:34},{x:13,y:2,w:11,h:8},{x:12,y:10,w:4,h:11},{x:22,y:10,w:4,h:11},{x:12,y:21,w:4,h:11},{x:22,y:21,w:4,h:11}];for(const r of rs)ctx.fillRect(r.x*32,r.y*32,r.w*32,r.h*32);ctx.strokeStyle='#5b7164';ctx.lineWidth=2;for(let i=0;i<5;i++){const p=pocketFor(i);ctx.strokeRect(p.x*32,p.y*32,p.w*32,p.h*32)}ctx.restore()}
function drawStructure(q){if(!q.alive)return;const p=screen(q.x,q.y);ctx.fillStyle={wall:'#698078',material:'#59b886',charge:'#63a7c9',turret:'#d7b95c',repair:'#a989d0'}[q.type];ctx.fillRect(p.x-q.w*15,p.y-q.h*15,q.w*30,q.h*30);ctx.fillStyle='#0b1115';ctx.fillRect(p.x-16,p.y-q.h*18,32,4);ctx.fillStyle='#a6e2b9';ctx.fillRect(p.x-16,p.y-q.h*18,32*Math.max(0,q.hp/q.maxHp),4);ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(q.tier,p.x,p.y+3)}
function drawEntity(e){if(!e.alive)return;const p=screen(e.x,e.y);ctx.fillStyle=e.kind==='hunter'?'#e66d43':(e.ai?'#9dd8bd':'#f4fbf7');ctx.beginPath();ctx.arc(p.x,p.y,e.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#071014';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#0b1115';ctx.fillRect(p.x-18,p.y-e.r-9,36,4);ctx.fillStyle=e.kind==='hunter'?'#f59a76':'#b9efcf';ctx.fillRect(p.x-18,p.y-e.r-9,36*Math.max(0,e.hp/e.maxHp),4)}
function drawPlacement(){if(!placing||role!=='builder')return;const wx=pointer.x+camera.x-W/2,wy=pointer.y+camera.y-H/2,gx=Math.floor(wx/32),gy=Math.floor(wy/32),d=defs[selected],ok=canPlace(state,state.builders[0],selected,gx,gy),p=screen((gx+d.size[0]/2)*32,(gy+d.size[1]/2)*32);ctx.fillStyle=ok?'#7ee3aa66':'#f0646466';ctx.fillRect(p.x-d.size[0]*16,p.y-d.size[1]*16,d.size[0]*32,d.size[1]*32)}
function draw(){if(!state)return;const focus=role==='hunter'?state.hunter:state.builders[0];camera.x+=(focus.x-camera.x)*.12;camera.y+=(focus.y-camera.y)*.12;camera.x=Math.max(W/2,Math.min(38*32-W/2,camera.x));camera.y=Math.max(H/2,Math.min(34*32-H/2,camera.y));drawTerrain();for(const q of state.structures)drawStructure(q);for(const b of state.builders)drawEntity(b);drawEntity(state.hunter);drawPlacement();const prep=Math.max(0,Math.ceil(CFG.prep-state.time));if(prep>0){ctx.fillStyle='#fff';ctx.font='800 34px sans-serif';ctx.textAlign='center';ctx.fillText(`Hunter released in ${prep}`,W/2,80)}}
function updateHud(){const b=state.builders[0],h=state.hunter,alive=state.builders.filter(x=>x.alive).length;document.querySelector('#roleLabel').textContent=role==='builder'?'BUILDER':'HUNTER';document.querySelector('#resources').textContent=role==='builder'?`M ${Math.floor(b.m)} · C ${Math.floor(b.c)}`:`Bounty ${Math.floor(h.bounty)} · HP ${Math.ceil(h.hp)}`;const left=Math.max(0,CFG.extraction-state.time);document.querySelector('#timer').textContent=`${Math.floor(left/60)}:${String(Math.floor(left%60)).padStart(2,'0')}`;document.querySelector('#remaining').textContent=`Builders ${alive}/5`;const center=Math.hypot(h.x-19*32,h.y-16*32)<68;shop.classList.toggle('hidden',role!=='hunter'||!center);if(role==='hunter'&&center)shopUi()}
window.EscapeeGame={restart:()=>begin(role||'builder'),pause:()=>paused=true,resume:()=>{paused=false;last=performance.now()},setMuted(){},getStatus:()=>state&&!state.winner?(paused?'paused':'playing'):'game-over'};
function finish(){if(!state?.winner||!result.classList.contains('hidden'))return;result.classList.remove('hidden');hud.classList.add('hidden');tray.classList.add('hidden');shop.classList.add('hidden');joystick.classList.add('hidden');buildBtn.classList.add('hidden');abilityBtn.classList.add('hidden');document.querySelector('#resultEyebrow').textContent=state.winner==='builders'?'HOLDFASTS SURVIVE':'THE HUNT IS COMPLETE';document.querySelector('#resultTitle').textContent=state.winner==='builders'?'Builders Win':'Hunter Wins';document.querySelector('#resultBody').textContent=`${Math.floor(state.time/60)}m ${Math.floor(state.time%60)}s · ${state.stats.destroyed} structures destroyed · ${Math.floor(state.stats.earned)} bounty earned.`}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state&&!paused&&!state.winner){acc+=dt;while(acc>=CFG.tick){step(state,command(),CFG.tick);acc-=CFG.tick}updateHud()}draw();finish();requestAnimationFrame(frame)}requestAnimationFrame(frame);
