export const CFG={tick:1/20,prep:30,extraction:720,overtime:600,cell:32,builderSpeed:150,hunterSpeed:174,dashSpeed:420,dashTime:.18,dashCooldown:5,structures:{wall:{name:'Barrier',m:30,c:0,hp:260,size:[1,1],upgrade:55},material:{name:'Material Rig',m:45,c:0,hp:120,size:[2,2],upgrade:70},charge:{name:'Charge Cell',m:55,c:10,hp:105,size:[2,2],upgrade:80},turret:{name:'Sentry Turret',m:50,c:25,hp:145,size:[1,1],upgrade:85},repair:{name:'Repair Beacon',m:65,c:40,hp:125,size:[1,1],upgrade:95}}};
const pockets=[{x:3,y:3,w:10,h:8,spawn:[7,7],gate:[12,6]},{x:24,y:2,w:10,h:8,spawn:[29,6],gate:[24,6]},{x:2,y:17,w:10,h:8,spawn:[7,21],gate:[11,20]},{x:25,y:17,w:10,h:8,spawn:[30,21],gate:[25,20]},{x:14,y:25,w:10,h:7,spawn:[19,28],gate:[19,25]}];
const rects=[{x:0,y:0,w:38,h:2},{x:0,y:32,w:38,h:2},{x:0,y:0,w:2,h:34},{x:36,y:0,w:2,h:34},{x:13,y:2,w:11,h:8},{x:12,y:10,w:4,h:11},{x:22,y:10,w:4,h:11},{x:12,y:21,w:4,h:11},{x:22,y:21,w:4,h:11}];let eid=1;
export function createMatch(role='builder',seed=1){const builders=pockets.map((p,i)=>({id:eid++,kind:'builder',team:'builders',ai:role==='hunter'||i>0,pocket:i,x:p.spawn[0]*32+16,y:p.spawn[1]*32+16,r:10,hp:100,maxHp:100,alive:true,m:90,c:20,buildCd:0}));const hunter={id:eid++,kind:'hunter',team:'hunter',ai:role==='builder',x:19*32,y:16*32,r:15,hp:560,maxHp:560,alive:true,bounty:0,damage:22,attackCd:0,speed:CFG.hunterSpeed,dashCd:0,dashLeft:0,level:{damage:0,hp:0,speed:0,siege:0,bounty:0}};const s={role,time:0,phase:'prep',winner:null,builders,hunter,structures:[],seed,stats:{destroyed:0,earned:0,generatedM:0,generatedC:0}};builders.forEach((b,i)=>place(s,b,'material',pockets[i].x+2,pockets[i].y+2,true));return s}
export function pocketFor(i){return pockets[i]}export function blockedTerrain(gx,gy){return rects.some(r=>gx>=r.x&&gy>=r.y&&gx<r.x+r.w&&gy<r.y+r.h)}
export function canPlace(s,b,type,gx,gy){const d=CFG.structures[type],p=pockets[b.pocket];if(!d||gx<p.x||gy<p.y||gx+d.size[0]>p.x+p.w||gy+d.size[1]>p.y+p.h)return false;for(let y=gy;y<gy+d.size[1];y++)for(let x=gx;x<gx+d.size[0];x++)if(blockedTerrain(x,y)||s.structures.some(q=>q.alive&&x>=q.gx&&y>=q.gy&&x<q.gx+q.w&&y<q.gy+q.h))return false;return true}
export function place(s,b,type,gx,gy,free=false){const d=CFG.structures[type];if(!canPlace(s,b,type,gx,gy)||(!free&&(b.m<d.m||b.c<d.c)))return false;if(!free){b.m-=d.m;b.c-=d.c}s.structures.push({id:eid++,kind:'structure',type,owner:b.id,pocket:b.pocket,gx,gy,w:d.size[0],h:d.size[1],x:(gx+d.size[0]/2)*32,y:(gy+d.size[1]/2)*32,hp:d.hp,maxHp:d.hp,tier:1,alive:true,age:0,shot:0});return true}
export function upgradeStructure(s,b,id){const q=s.structures.find(x=>x.id===id&&x.owner===b.id&&x.alive);if(!q||q.tier>=4)return false;const cost=CFG.structures[q.type].upgrade*q.tier;if(b.m<cost||b.c<Math.max(0,cost*.25-10))return false;b.m-=cost;b.c-=Math.max(0,cost*.25-10);q.tier++;q.maxHp*=1.55;q.hp=q.maxHp;return true}
export function buyHunter(s,key){const h=s.hunter,n=h.level[key]||0,cost=70+n*65;if(h.bounty<cost)return false;h.bounty-=cost;h.level[key]=n+1;if(key==='damage')h.damage*=1.22;if(key==='hp'){h.maxHp+=110;h.hp+=110}if(key==='speed')h.speed+=15;return true}
function collideTerrain(x,y,r){for(let gy=Math.floor((y-r)/32);gy<=Math.floor((y+r)/32);gy++)for(let gx=Math.floor((x-r)/32);gx<=Math.floor((x+r)/32);gx++)if(blockedTerrain(gx,gy))return true;return false}
function moveEntity(s,e,dx,dy,dt){const speed=e.kind==='hunter'&&e.dashLeft>0?CFG.dashSpeed:(e.speed||CFG.builderSpeed),len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;let nx=e.x+dx*speed*dt,ny=e.y+dy*speed*dt;const blocks=e.kind==='hunter'?s.structures.filter(q=>q.alive&&q.type==='wall'):[];if(!collideTerrain(nx,e.y,e.r)&&!blocks.some(q=>Math.abs(nx-q.x)<q.w*16+e.r&&Math.abs(e.y-q.y)<q.h*16+e.r))e.x=nx;if(!collideTerrain(e.x,ny,e.r)&&!blocks.some(q=>Math.abs(e.x-q.x)<q.w*16+e.r&&Math.abs(ny-q.y)<q.h*16+e.r))e.y=ny}
function damageStructure(s,q,amt){q.hp-=amt;const earn=amt*(.08+s.hunter.level.bounty*.015);s.hunter.bounty+=earn;s.stats.earned+=earn;if(q.hp<=0){q.alive=false;s.stats.destroyed++}}
function attackHunter(s){const h=s.hunter;if(h.attackCd>0||s.phase==='prep')return;let targets=[...s.builders.filter(b=>b.alive),...s.structures.filter(q=>q.alive)].filter(t=>Math.hypot(t.x-h.x,t.y-h.y)<h.r+(t.r||Math.max(t.w,t.h)*16)+18);targets.sort((a,b)=>(a.kind==='builder'?-10:0)-(b.kind==='builder'?-10:0)+Math.hypot(a.x-h.x,a.y-h.y)-Math.hypot(b.x-h.x,b.y-h.y));const t=targets[0];if(!t)return;h.attackCd=.52;if(t.kind==='builder'){t.hp-=h.damage;if(t.hp<=0){t.alive=false;t.hp=0;h.bounty+=120}}else damageStructure(s,t,h.damage*(1+h.level.siege*.18))}
function updateStructures(s,dt){for(const q of s.structures){if(!q.alive)continue;q.age+=dt;q.shot-=dt;const b=s.builders.find(x=>x.id===q.owner);if(!b?.alive)continue;if(q.type==='material'){const v=(1.25+.7*(q.tier-1))*dt;b.m+=v;s.stats.generatedM+=v}if(q.type==='charge'){const v=(.34+.22*(q.tier-1))*dt;b.c+=v;s.stats.generatedC+=v}if(q.type==='repair'&&b.c>0){const t=s.structures.find(x=>x.alive&&x.owner===b.id&&x.hp<x.maxHp&&Math.hypot(x.x-q.x,x.y-q.y)<100+q.tier*18);if(t){const v=Math.min(t.maxHp-t.hp,(6+q.tier*4)*dt,b.c*5);t.hp+=v;b.c-=v/5}}if(q.type==='turret'&&q.shot<=0&&s.phase!=='prep'&&Math.hypot(s.hunter.x-q.x,s.hunter.y-q.y)<135+q.tier*18){q.shot=Math.max(.22,.78-q.tier*.1);s.hunter.hp-=10+q.tier*6}}}
function hunterAI(s,dt){const h=s.hunter;if(!h.ai||s.phase==='prep')return;const center={x:19*32,y:16*32};if(h.hp<h.maxHp*.34||h.bounty>130){moveEntity(s,h,center.x-h.x,center.y-h.y,dt);if(Math.hypot(h.x-center.x,h.y-center.y)<58){h.hp=Math.min(h.maxHp,h.hp+55*dt);for(const k of ['damage','hp','siege','speed'])if(buyHunter(s,k))break}return}const t=s.builders.filter(b=>b.alive).sort((a,b)=>Math.hypot(a.x-h.x,a.y-h.y)-Math.hypot(b.x-h.x,b.y-h.y))[0];if(t)moveEntity(s,h,t.x-h.x,t.y-h.y,dt)}
function builderAI(s,b,dt){if(!b.ai||!b.alive)return;const p=pockets[b.pocket];b.buildCd-=dt;const near=Math.hypot(s.hunter.x-b.x,s.hunter.y-b.y)<210;if(near){moveEntity(s,b,p.spawn[0]*32+16-b.x,p.spawn[1]*32+16-b.y,dt);const wall=s.structures.find(q=>q.owner===b.id&&q.type==='wall'&&q.alive);if(wall&&Math.hypot(wall.x-b.x,wall.y-b.y)<80&&b.m>1){const v=Math.min(wall.maxHp-wall.hp,25*dt,b.m*2);wall.hp+=v;b.m-=v/2}return}if(b.buildCd>0)return;const own=s.structures.filter(q=>q.owner===b.id&&q.alive),count=t=>own.filter(q=>q.type===t).length;let type=null,gx=p.x+2+(s.seed+b.id+own.length*3)%Math.max(1,p.w-3),gy=p.y+2+(s.seed*2+b.id+own.length*2)%Math.max(1,p.h-3);if(count('wall')<2){type='wall';gx=p.gate[0]-(b.pocket===1||b.pocket===3?0:1);gy=p.gate[1]}else if(count('charge')<1)type='charge';else if(count('turret')<2)type='turret';else if(count('material')<2)type='material';else if(count('repair')<1)type='repair';else{const q=own.sort((a,c)=>a.tier-c.tier)[0];if(q)upgradeStructure(s,b,q.id);b.buildCd=1.5;return}for(let tries=0;tries<20;tries++){if(place(s,b,type,gx,gy)){b.buildCd=1.2;return}gx=p.x+1+(gx-p.x+1)%Math.max(2,p.w-2);gy=p.y+1+(gy-p.y+(tries%3))%Math.max(2,p.h-2)}b.buildCd=1}
export function step(s,commands,dt=CFG.tick){if(s.winner)return;for(const c of commands){if(c.type==='move'){const e=c.actor==='hunter'?s.hunter:s.builders[c.actor];if(e?.alive)moveEntity(s,e,c.x,c.y,dt)}if(c.type==='place')place(s,s.builders[c.actor],c.structure,c.gx,c.gy);if(c.type==='upgrade')upgradeStructure(s,s.builders[c.actor],c.id);if(c.type==='dash'&&s.hunter.dashCd<=0){s.hunter.dashCd=CFG.dashCooldown;s.hunter.dashLeft=CFG.dashTime}if(c.type==='buy')buyHunter(s,c.key)}s.time+=dt;if(s.time>=CFG.prep)s.phase=s.time>=CFG.overtime?'overtime':'hunt';s.hunter.attackCd=Math.max(0,s.hunter.attackCd-dt);s.hunter.dashCd=Math.max(0,s.hunter.dashCd-dt);s.hunter.dashLeft=Math.max(0,s.hunter.dashLeft-dt);updateStructures(s,dt);hunterAI(s,dt);for(const b of s.builders)builderAI(s,b,dt);attackHunter(s);if(s.hunter.hp<=0){s.hunter.alive=false;s.winner='builders'}else if(!s.builders.some(b=>b.alive))s.winner='hunter';else if(s.time>=CFG.extraction)s.winner='builders'}
